version: '3.8'
services:
  app:
    image: inventory-management-system
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: inventoryDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
